//Author: ChocolateCircus445
var en = {
  langCode: "en",
  langName: "English",
  bg_aerial_seashore_rocks: "Aerial View of Seashore with Rocks",
  bg_new_york_skyline: "New York City Skyline",
  bg_mountains_cloudy_skies: "Mountains with Cloudy Skies",
  bg_devils_tower_1: "Devil's Tower 1",
  bg_devils_tower_2: "Devil's Tower 2",
  bg_mount_rushmore: "Mount Rushmore",
  bg_butte_along_river: "Butte along River",
  bg_white_brick_wall: "White Brick Wall",
  bg_rocky_beach: "Rocky Beach",
  se_biglobe: "BIGLOBE (Japanese only)",
  redacted: "[REDACTED]",
  timeFormat: "$%h:%m| %x",
  dateFormat: "%w, %l/%d/%y",
  weekdays: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
  timeSuffixes: ["AM", "PM"],
  is24hr: false,
  locationServiceFail: "Location services are not working right now.",
  bgCourtesy: "This background is courtesy of %0",
  search: "Search!",
  menu: "Menu",
  about: "About",
  bookmarks: "Bookmarks",
  settingsGear: "\u2699\ufe0f Settings",
  settings: "Settings",
  language: "Language",
  background: "Background",
  custom: "Custom",
  save: "\ud83d\udcbe Save",
  clock24hr: "Use military time",
  searchEngine: "Search Engine",
  protectsPrivacy: "Protects privacy",
  notProtectsPrivacy: "Does not protect privacy",
  featuresPlanned: "Features Planned",
  addBM: "Add a bookmark",
  noInternet: "No internet",
  mitLicense: ""
}
langs.en = "en";
