//Author: ChocolateCircus445
var es = {
  langCode: "es",
  langName: "Espa\u00f1ol",
  bg_aerial_seashore_rocks: "Vista A\u00e9rea de Costa con Rocas",
  bg_new_york_skyline: "Nueva York de Horizonte",
  bg_mountains_cloudy_skies: "Monta\u00f1as con Cielo Nublado",
  bg_devils_tower_1: "Torre del Diablo 1",
  bg_devils_tower_2: "Torre del Diablo 2",
  bg_mount_rushmore: "Monta\u00f1a Rushmore",
  bg_butte_along_river: "Butte a lo largo un R\u00edo",
  bg_white_brick_wall: "Pared Ladrillo Blanco",
  bg_rocky_beach: "Playa Rocosa",
  se_biglobe: "BIGLOBE (S\u00f3lo japon\u00e9s)",
  redacted: "[REDACTED]",
  timeFormat: "$%h:%m| %x",
  dateFormat: "%w, %d/%l/%y",
  weekdays: ["domingo", "lunes", "martes", "mi\u00e9rcoles", "jueves", "s\u00e1bado", "domingo"],
  timeSuffixes: ["a.m.", "p.m."],
  is24hr: false,
  locationServiceFail: "Servicios locaci\u00f3n no estas functionar ahora mismo.",
  bgCourtesy: "Esto papel pintado es cortes\u00eda de %0",
  search: "Buscar!",
  menu: "Men\u00fa",
  about: "Acerca de (Ingl\u00e9s)",
  bookmarks: "Marcadores de libros",
  settingsGear: "\u2699\ufe0f Preferencias",
  settings: "Preferencias",
  language: "Idioma",
  background: "Fondo",
  custom: "Personalizado",
  save: "\ud83d\udcbe Guardar",
  clock24hr: "Utilizar un 24 hora reloj",
  searchEngine: "Buscador",
  protectsPrivacy: "Proteger la privacidad",
  notProtectsPrivacy: "No proteger la privacidad",
  featuresPlanned: "Features Planned",
  addBM: "A\u00f1adir un marcador de libro",
  noInternet: "No internet",
}
langs.es = "es";
